name: CI
on: [ push, pull_request ]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.10" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: run poetry image
        uses: abatilo/actions-poetry@v2.0.0

      - name: install dependencies
        run: poetry install

      - name: Format code (isort)
        run: isort .

      - name: Format code (black)
        run: black .